# Generated by Django 5.2.3 on 2025-06-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='uuid',
        ),
    ]
