# Generated by Django 5.2.3 on 2025-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_rename_id_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
