# Generated by Django 5.2.1 on 2025-05-29 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
