# Generated by Django 5.2.1 on 2025-06-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0009_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
